"""MeetingRoom description sdded

Revision ID: 098c0667998e
Revises: a26ea24f9ead
Create Date: 2024-02-09 21:25:10.196316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098c0667998e'
down_revision = 'a26ea24f9ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
